sudo: required
services: 
    - docker

before_install:
    - docker build -t gavinwilson/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true gavinwilson/react-test npm test

after_success:
    - docker build -t gavinwilson/multi-client ./client
    - docker build -t gavinwilson/multi-nginx ./nginx
    - docker build -t gavinwilson/multi-server ./server
    - docker build -t gavinwilson/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push gavinwilson/multi-client
    - docker push gavinwilson/multi-nginx
    - docker push gavinwilson/multi-server
    - docker push gavinwilson/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-2-662013788334
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY